name: Verify Quarkus Build Caching Extension
permissions:
  contents: read

on:
  schedule:
    # Every Sunday at 9.00am - scheduled to test against latest Quarkus version
    - cron: "0 9 * * 0"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  verification:
    name: Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up JDK 17
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install Quarkus snapshots
        uses: quarkusio/install-quarkus-snapshots-action@de83c2a9a1528f92fa835160b1239c5bdb680ded # main
      - name: Build with Maven
        run: |
          ./mvnw --batch-mode clean package integration-test -Drun-latest-it=true
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}
      - name: Upload integration tests reports (on failure only)
        if: ${{ failure() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: Integration tests logs
          path: |
            target/it/**/*.log
